version: '3'
name: 'go-hactiv8'

services:

  app:
    container_name: 'go-hactiv8-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DSN: "host=postgres port=5432 user=root password=root dbname=order_by sslmode=disable timezone=UTC connect_timeout=5"
    networks:
      - go-hactiv8
    deploy:
      mode: replicated
      replicas: 1

  db:
    container_name: 'postgres'
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_by
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - go-hactiv8

networks:
  go-hactiv8:
    driver: bridge

volumes:
  postgres:
    driver: local
