version: '3'
name: 'go-hactiv8'

services:

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - go-hactiv8
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db

  db:
    container_name: 'postgres'
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go_hactiv8
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - go-hactiv8

networks:
  go-hactiv8:
    driver: bridge

volumes:
  postgres:
    driver: local